### PR TITLE
Add Gradle build script; Update .gitignore to ignore Gradle build files.

### PR DESCRIPTION
**Pull request by XerTheSquirrel**
This adds a build script which allows for building with Gradle.

Additionally .gitignore is updated to ignore Gradle's build files.

### CODE REVIEW

**Comment by pselle** [comment]
In the java agent, you said:
> For simplicity I will refer users to the Gradle example in the example repository from the readme rather than duplicating that information (since Gradle is simple and easy to read compared to Maven's XML).
want to add that link from the README here then?

**Comment by XerTheSquirrel** [comment]
I was thinking in the main project's README: having

```
# Installation & usage

This documentation mostly refers to using Maven for your project, if you
are using Gradle then you can use the example located at:
<https://github.com/iopipe/examples/blob/master/java/build.gradle>.
```

I can also add a note to the README here on using the Example project but Gradle uses an alternative location so if Serverless can have an alternative OR artifact then that is good.

**Comment by pselle** [comment]
@XerTheSquirrel That makes sense! Yeah, most people get to this repo (or one would think ....) after being on the agent repo

**Comment by XerTheSquirrel** [comment]
@pselle I do not believe serverless allows you to specify an alternative configuration file, I cannot find any mention of such a setting. This means the `sls` will not be available unless the files are renamed accordingly or a symlink is created.

**Comment by XerTheSquirrel** [comment]
@pselle Okay, I updated `serverless.yml` as per your suggestion on Slack and updated the readme!

**Pull request merged**
